name: Everyday Kayla
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28657
title: Everyday Kayla
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#131417'
    - '#d2d2d3'
    - '#9d9d9e'
    - '#555658'
  brandStrength: 1
  lightness: 0.89165492169559
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
