name: Everyday Kayla
favicon: null
layout_spectrum: 0.75042
typography_spectrum: 0.28657
title: Everyday Kayla
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2e6d8'
    - '#000000'
    - '#a7b1a8'
    - '#678b97'
    - '#484944'
  brandStrength: 0.375
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
